[build]
  command = "npx prisma generate && npm cache clean --force && npm run build"
  publish = "build"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]
